# Generated by Django 3.0.2 on 2020-01-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_auto_20200104_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Timestamp',
        ),
    ]
