# Generated by Django 3.0.2 on 2020-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_remove_employee_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Timestamp',
            field=models.DateField(default=None),
        ),
    ]
