# Generated by Django 3.0.2 on 2020-01-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_employee_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Timestamp',
        ),
    ]
