# Generated by Django 3.0.2 on 2020-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_employee_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
