# Generated by Django 3.0.2 on 2020-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_auto_20200105_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Timestamp',
            field=models.DateField(default=None),
        ),
    ]
